### ISSUE TITLE
Adding user to org.yaml does not generate an invite to join the org

### ISSUE THREAD

**Issue by james-jwu** [kubeflow/internal-acls#148]
I submitted and merged a PR that adds "james-jwu" to org.yaml. I expect that I am able to access https://github.com/orgs/kubeflow/teams/pipelines/members, but cannot. It looks like I am not added to kubflow/members, and I should receive an invite to join but did not.

**Comment by jlewi** [comment]
The sync looks to have completed successfully; here are the logx.

[synclogs.txt](https://github.com/kubeflow/internal-acls/files/3591973/synclogs.txt)

**Comment by jlewi** [comment]
Actually looks like there is an error from the most recent sync.

```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure kubeflow members: all team members/maintainers must also be org members: imjohnbo","time":"2019-09-09T18:20:32Z"}
```
So looks like imjohnbo is a member of a group but not the org so the config is invalid.

@james-jwu do you want to submit a PR to fix this.

**Comment by jlewi** [comment]
Reopen still broken

```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure kubeflow members: all team members/maintainers must also be org members: cspavlou","time":"2019-09-09T22:50:33Z"}
```

Probably due to #145

**Comment by jlewi** [comment]
@james-jwu Can you open up an issue to also add your py_test to the presubmits?

Here's [instructions](https://github.com/kubeflow/testing#python-function) basically you need to add an Argo workflow that would run the test you wrote. 

You could take a look at this unittest workflow for kubeflow/kubeflow
https://github.com/kubeflow/kubeflow/blob/5b652b18892c7b49af48ecc365b0af1080e0cb06/prow_config.yaml#L109 
(Note its using ksonnet to express the Argo workflow; we don't want to use ksonnet anymore).

**Comment by james-jwu** [comment]
@jlewi I opened issue #151. I will fix this issue by updating the org.yaml file, and work on #151 afterwards.
