### ISSUE TITLE
GitHub sync is failing

### ISSUE THREAD

**Issue by jlewi** [kubeflow/internal-acls#154]
/kind bug

Latest run of the cron job failed with

```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:201","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure kubeflow members: 1 errors: [status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership\"}]","time":"2019-09-13T15:20:30Z"}

```

**Comment by jlewi** [comment]
We are using 
gcr.io/k8s-prow/peribolos@sha256:ffb1e428ec88513ab3345e887be958ec3bb112b2e23a05b6088e53b18046f4a5

Lets try a more recent image.

Now I'm getting the error

```
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership\"}","file":"prow/cmd/peribolos/main.go:441","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(kubeflow, , false) failed","time":"2019-09-13T15:32:47Z"}
```

It looks like the user doesn't exist or maybe they deleted their account.

**Comment by clarketm** [comment]
@jlewi - are you still getting sync error after the image update? That error message https://github.com/kubeflow/internal-acls/issues/154#issuecomment-531289684 is misleading, because in the case of a **404** processing will continue ([ref](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos/main.go#L443-L447)).

**Comment by jlewi** [comment]
@clarketm thanks I will try updating the image and see if that fixes the 404 issue.
