### ISSUE TITLE
Automate syncing of Google Groups

### ISSUE THREAD

**Issue by jlewi** [kubeflow/internal-acls#22]
We should automate syncing of a subset of groups.

The subset of groups should be restricted to non critical groups (e.g. not google-kubeflow-admins).

We should create a suitable bot account and make this a manager of the groups that we want to administer.

We should then setup a restricted cluster that has the appropriate credentials. Ideally we can setup a GCP service account.

We should use a restricted cluster and follow the process for setting up peribolos
kubeflow/community#55

**Comment by jlewi** [comment]
I think there are multiple pieces to this

1. Create a simple go binary to use the [directory API](https://developers.google.com/admin-sdk/directory) to
     1. Create groups if needed
     1. Add/Remove members to match the config file
1. Create a service account with appropriate permissions to do the sync.
1. Create a K8s deployment
     1. load groups from YAML
1. Use ACM to synchronize the configs to the cluster

**Comment by jlewi** [comment]
/cc @Jeffwan @terrytangyuan @animeshsingh @yanniszark 
Just an FYI I'm going to be asking for help on this issue the next time you get blocked needing to be added to a Google group.

**Comment by Bobgy** [comment]
Just realized the directory api is related to gsuite admin-sdk: https://developers.google.com/admin-sdk/directory.
From first glance, I thought it just let you read directories.

**Comment by jlewi** [comment]
@Bobgy I think you can manage groups
https://developers.google.com/admin-sdk/directory/v1/guides/manage-group-members

**Comment by jlewi** [comment]
Fixed.
