### ISSUE TITLE
Configure peribolos to sync repo permissions and teams

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/internal-acls#228]
Could anyone here grant me write access to the following two repos?

* https://github.com/kubeflow/common
* https://github.com/kubeflow/xgboost-operator/

Currently I am listed as maintainer both of these two repos under team "xgboost-operator-team" and "common-team" as specified in [org.yaml](https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml). However, I don't have write access to these two repos yet. I need these access to:

* Manage storyboards and releases,
* Add other existing members or invite new members to the corresponding team (e.g. new reviewers and approvers),
* Set up CI/CD.

/cc @jlewi

**Comment by jlewi** [comment]
> Add other existing members or invite new members to the corresponding team (e.g. new reviewers and approvers),

Can this be done through OWNERs files? 

> Set up CI/CD.

Can this be done through PRs modifying the appropriate config files?
https://github.com/kubeflow/testing#setting-up-a-kubeflow-repository-to-use-prow-a-idprow-setupa

> Manage storyboards and releases,

What GitHub roles provide the least privilege to accomplish what you need?

Can membership and repo permissions be managed through GitOps to make it easier to scale and manage?

We are using [peribolos](https://github.com/kubernetes/test-infra/blob/eb64dfdaf1fb86024ad153b6e4caef7135cd3fdf/prow/cmd/peribolos/README.md) to declaratively manage GitHub permissions.

**Comment by terrytangyuan** [comment]
Got it. I didn’t know we are using peribolos to manage the permissions, which definitely seems more scalable and manageable. I believe the corresponding teams I am in are missing a “repos” field. I’ll give that a try soon. Thanks!

**Comment by terrytangyuan** [comment]
Per comment in https://github.com/kubeflow/internal-acls/pull/229#issuecomment-605516105, it seems like we might not have peribolos configured to sync repo permissions yet. I am re-opening this issue to track that.

**Comment by jlewi** [comment]
We should already be sync'ing teams

```
           - /app/prow/cmd/peribolos/app.binary.runfiles/io_k8s_test_infra/prow/cmd/peribolos/linux_amd64_pure_stripped/app.binary  
            - --fix-teams 
            - --fix-team-members 
            - --fix-org-members 
            - --config-path=/src/kubeflow/internal-acls/github-orgs/kubeflow/org.yaml
            - --github-token-path=/secret/github-token/github_token
            - --required-admins=jlewi
            - --required-admins=abhi-g
            - --required-admins=google-admin
            - --required-admins=googlebot
            - --required-admins=richardsliu
            - --confirm=true
```

**Comment by jlewi** [comment]
It looks like peribolos has two options
* fix-team-repos - fix team permissions on repos
* fix-repos - create/update/delete repos

So we probably want the fix-team-repos permission.

**Comment by jlewi** [comment]
The job is currently failing. 
Here are the logs
[logs.txt](https://github.com/kubeflow/internal-acls/files/4660526/logs.txt)

The problem is that ajayalfred is not a user.

```
{"component":"peribolos","error":"status code 422 not one of [200], body: {\"message\":\"The request could not be processed.\",\"documentation_url\":\"https://developer.github.com/v3/orgs/members/#add-or-update-organization-members
hip\"}","file":"prow/cmd/peribolos/main.go:441","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(kubeflow, ajayalfred, false) failed","time":"2020-05-21T03:50:56Z"}
```

**Comment by jlewi** [comment]
I updated the cron job to  run with fix-team-repos.

**Comment by jlewi** [comment]
Per: kubernetes/test-infra#14321 it looks like we are using an outdated peribolos image; on newer images it keeps going on error.

**Comment by jlewi** [comment]
Looks like kubernetes/test-infra/issues#17671 its still an issue with peribolos not continuing

**Comment by terrytangyuan** [comment]
This has been fixed by #250.

**Comment by jlewi** [comment]
Confirmed this is working.
https://github.com/kubeflow/internal-acls/pull/251
Submitted a new team mxnet-operator-team and that team now exists.

**Comment by terrytangyuan** [comment]
@jlewi Yes and repo permissions are also correct! Thanks for all the efforts!
