### ISSUE TITLE
Add mxnet-operator to repos managed by project-maintainers team

### ISSUE THREAD

**Issue by terrytangyuan** [kubeflow/internal-acls#233]
[mxnet-operator](https://github.com/kubeflow/mxnet-operator) is missing from the [list of repos managed by project-maintainers team](https://github.com/orgs/kubeflow/teams/project-maintainers/repositories). 

/cc @abhi-g @jlewi @richardsliu 

Could you add it since you are the maintainers of project-maintainers team?

**Comment by jlewi** [comment]
@terrytangyuan Can you open up a PR please to add it to the team?

**Comment by terrytangyuan** [comment]
@jlewi I don't think the list of repos is managed by the "project-maintainers" team in  [org.yaml](https://github.com/kubeflow/internal-acls/blob/master/github-orgs/kubeflow/org.yaml) yet. Should I go ahead and add the list of repos to that team? I am uncertain whether peribolos has been configured to sync repo permissions as discussed in https://github.com/kubeflow/internal-acls/issues/228.

**Comment by jlewi** [comment]
@terrytangyuan I'm guessing peribolos has not been configured but we could/should probably enable it if that's not the case.
