### ISSUE TITLE
Q: how should GAM CLI be setup?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/internal-acls#288]
I was added as admin, but I cannot set up my GAM CLI properly.

I was following GAM install guide in https://github.com/jay0lee/GAM and I got
```
GAM is now installed. Are you ready to set up a Google API project for GAM? (yes or no) yes

Go to the following link in your browser:

	https://gam-shortn.appspot.com/9zgvtf

Enter verification code:
```

When clicking the url, it tells me I don't have permission to create a project.

**Comment by jlewi** [comment]
@Bobgy Where are you trying to create a project? I believe you are just configuring a GCP project to use for charging quota.

See also: kubeflow/internal-acls#22 it might also make more sense to just focus on writing a simple go binary to use the Directory API rather than dealing with gam.

**Comment by Bobgy** [comment]
I agree #22 will be a better long term solution. If this is hard to achieve, let's just do that.

**Comment by Bobgy** [comment]
OK, I figured out how to set it up.

Prerequisite is I need to get an kubeflow.org email addresss.
I got `gongyuan@kubeflow.org`.

Then I can follow instructions in https://github.com/jay0lee/GAM/wiki to set up the tool. Specifically, it needs to create a "GAM Project" Google Cloud project in kubeflow.org. After following all initial setup, I can run the sync_group script.
