### ISSUE TITLE
GitHub Org Sync appears to be broken again

### ISSUE THREAD

**Issue by jlewi** [kubeflow/internal-acls#359]
Looks like the sync is broken again. There doesn't appear to be the group @kubeflow/wg-notebook-leads which was added in #358

I suspect its due to either #358 or #353 

/cc @thesuperzapper @chensun @PatrickXYS

**Comment by PatrickXYS** [comment]
That's weird, all in #353 is to make a github account as member and create a new team.

**Comment by chensun** [comment]
The error is
```
{"component":"peribolos","error":"status code 404 not one of [200], body: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/orgs#set-organization-membership-for-a-user\"}","file":"prow/cmd/peribolos/main.go:484","func":"main.configureOrgMembers.func1","level":"warning","msg":"UpdateOrgMembership(kubeflow, kandrio98, false) failed","time":"2020-10-20T17:31:12Z"}
```

Looks like the user `kandrio98` recently changed their GitHub username to `kandrio`. Will sent a fix shortly.

**Comment by thesuperzapper** [comment]
@chensun just wanted to check, where can you view those logs?

**Comment by chensun** [comment]
> @chensun just wanted to check, where can you view those logs?

I'm not sure if you might have access. But this sync job runs in a cluster `kf-admin-cluster`. I got the error from the pod log.
