### ISSUE TITLE
Sync issue happened for wg-manifests and wg-deployment

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/internal-acls#384]
After [this PR ](https://github.com/kubeflow/internal-acls/pull/382)merged, 

we should have wg-manifests and wg-deployment Github Team established, 

given this query, https://github.com/orgs/kubeflow/teams?query=wg-

It's obviously sync script does not work, I'm guessing the issue happened before, happened again.

/cc @chensun @jlewi @Bobgy

**Comment by Bobgy** [comment]
/assign
I'll investigate now

**Comment by Bobgy** [comment]
Found error
```
ValueError: chensun is not in the allowed set of admins. Allowed admins is Bobgy, google-admin, googlebot, james-jwu, jlewi, k8s-ci-robot, richardsliu, rmgogogo, theadactyl
```
I'll prioritize https://github.com/kubeflow/internal-acls/issues/346 after immediate work items for Kubeflow 1.2

**Comment by Bobgy** [comment]
Hmm, the change was correct in https://github.com/kubeflow/internal-acls/pull/376, but the running job hasn't been updated. I'll investigate further.

**Comment by PatrickXYS** [comment]
Maybe adding @chensun to the kubeflow org, and then check out the cron job to see how it goes.

**Comment by PatrickXYS** [comment]
I think we can improve the process, find a way to expose logs / errors / issues to non-google folks, thus, it will save time for google-admin to check those logs as well

**Comment by Bobgy** [comment]
OK, I found the problem, the validate.py change needs to be manually updated by https://github.com/kubeflow/internal-acls/blob/e4ad312993bbed0ba9a54b92258aad929b338d3c/github-orgs/manifests/Makefile#L10

I've updated that, the next sync should work

**Comment by Bobgy** [comment]
> I think we can improve the process, find a way to expose logs / errors / issues to non-google folks, thus, it will save time for google-admin to check those logs as well

I think the blocker is that fixing anything there is high privilege, so you'll need to wait for a google-admin to do that, just exposing the logs might not be enough, but exposing logs might be helpful to let community members find a fix and contribute a PR...

Any ideas for a good way to expose those logs?

**Comment by Bobgy** [comment]
There's one more problem
```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure kubeflow members: kubeflow must specify {[jlewi james-jwu google-admin googlebot] true} as admins, missing [jlewi]","severity":"fatal","time":"2020-11-05T02:50:10Z"}
```

**Comment by Bobgy** [comment]
/reopen
Still not working
> {"component":"peribolos","file":"prow/cmd/peribolos/main.go:202","func":"main.main","level":"fatal","msg":"Configuration failed: failed to configure kubeflow members: authenticated user jlewi is not an admin of kubeflow","severity":"fatal","time":"2020-11-05T03:10:19Z"}

**Comment by Bobgy** [comment]
The sync was successful

**Comment by PatrickXYS** [comment]
> > I think we can improve the process, find a way to expose logs / errors / issues to non-google folks, thus, it will save time for google-admin to check those logs as well
> 
> I think the blocker is that fixing anything there is high privilege, so you'll need to wait for a google-admin to do that, just exposing the logs might not be enough, but exposing logs might be helpful to let community members find a fix and contribute a PR...
> 
> Any ideas for a good way to expose those logs?

I can come up with some ideas including giving viewer access, but looks like the GKE cluster cronjob is running is not used internally, I don't have a good idea
