### ISSUE TITLE
github org invitation not yet received

### ISSUE THREAD

**Issue by subodh101** [kubeflow/internal-acls#396]
What?
Here is the PR: https://github.com/kubeflow/internal-acls/pull/356

cc: @PatrickXYS @jlewi @Bobgy

**Comment by PatrickXYS** [comment]
Should be sync issue... I don't know why the issue happens much frequently recently, can we improve the process to help google folks get rid of the oncall-sync stuff?

/cc @Bobgy

**Comment by jlewi** [comment]
I'm no longer a GitHub org admin so I can't check to see whether the invite got sent. 

One thing that might help which may or may not be related to this particular issue is better validation on presubmits #392. This would hopefully catch sync breaking changes before they are merged.

/cc @chensun @PatrickXYS

**Comment by chensun** [comment]
No error reported from recent syncs.
I do see a log line as: 
```
{"component":"peribolos","file":"prow/cmd/peribolos/main.go:476","func":"main.configureOrgMembers.func1","level":"info","msg":"Waiting for subodh101 to accept invitation to kubeflow","severity":"info","time":"2020-11-07T20:55:00Z"}
```

**Comment by Bobgy** [comment]
@subodh101 I can see your name in "pending invitation" state on github UI for Kubeflow org, so it's not the sync's problem.

Please confirm your email's trash first

**Comment by subodh101** [comment]
@Bobgy 
I confirm I can't find the email even in the trash. This seems weird.

**Comment by Bobgy** [comment]
@subodh101 let me manually resend the invitation to you

**Comment by subodh101** [comment]
It may have sent the invitation to my college id.
But my primary email was subodh.pushkar@gmail.com only. However, I have deleted my college id now just in case.
Could you use the email to send the invitation? Also, I hope that doesn't break the sync.

**Comment by Bobgy** [comment]
I've deleted your invitation again, the sync will resend it soon. And FYI, the invitation email is completely a github feature. The sync is only responsible for initiating the invitation, if the rest of job goes wrong, it's on github side. So I don't think it will confuse the sync.

**Comment by subodh101** [comment]
Thank you!
Got the invitation. :)

**Comment by Bobgy** [comment]
@subodh101 you are welcome! Thank you for your contributions!
