### ISSUE TITLE
Update or deprecate member_organizations.yaml?

### ISSUE THREAD

**Issue by Bobgy** [kubeflow/internal-acls#405]
> I believe that file was there less to offer explicit permins, and more to allow community members to note their involvement in the project. That being said, it's never been widely used and should probably be deprecated. @yanniszark or @Bobgy would either of you want to make a proposal to that effect?

_Originally posted by @theadactyl in https://github.com/kubeflow/internal-acls/issues/401#issuecomment-726216347_

The [member_organiziations.yaml](https://github.com/kubeflow/community/blob/master/member_organizations.yaml) hasn't been updated for a while, I can see a lot of stale information there. Shall we keep it updated or stop using it altogether? I don't see people using it anyway, but I could be wrong.

**Comment by Bobgy** [comment]
/cc @jbottum @jlewi @Jeffwan @PatrickXYS @terrytangyuan @animeshsingh 
Any insights?

**Comment by terrytangyuan** [comment]
I believe people are still updating it. I would prefer updating it so that we know who we can contact to for each organizations. The `hiringUrl` might also be useful for some folks in the community who have experience in Kubeflow and are looking for relevant job opportunities.

**Comment by jlewi** [comment]
I believe one of the main use cases for 
https://github.com/kubeflow/community/blob/master/member_organizations.yaml is to generate a list of all the organizations to acknowledge; e.g. generate slides like this one
https://docs.google.com/presentation/d/1i_xG2SpJAmqpsloD62C_Ls55OipZJ1pcgFVuciBUqnU/edit#slide=id.g560b73ae6c_0_214

So we probably need something to serve the purpose of collecting logos for such slides.
