### ISSUE TITLE
REQUEST: New membership for rimolive

### ISSUE THREAD

**Issue by rimolive** [kubeflow/internal-acls#627]
/kind area/process

Please read the [guide lines](https://www.kubeflow.org/docs/about/contributing/#joining-the-community) for joining the Kubeflow GitHub org before opening an issue

**Please provide links to PRs or other contributions (2-3):**
https://github.com/kubeflow/kfp-tekton/pull/977
https://github.com/kubeflow/kfp-tekton/pull/1378

**Please list 2 existing members who are sponsoring your membership:**
@Tomcli
@yhwang 

**Please test your PR**

Run

```
cd github_orgs
pytest test_org_yaml.py
```
Include the output in the PR

**Additional Instructions**

After your PR is merged please wait at least 1 hour for changes to propogate. 

If after an hour you haven't recieved an invite to join the GitHub org please open an issue.

You can contact build copy in #buildcop in kubeflow.slack.com

**Comment by rimolive** [comment]
pytest result:
```
=============================================================================== test session starts ================================================================================
platform linux -- Python 3.11.6, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/rmartine/Development/github-projects/internal-acls/github-orgs
plugins: forked-1.6.0, cov-3.0.0, xdist-2.5.0
collected 1 item                                                                                                                                                                   

test_org_yaml.py .                                                                                                                                                           [100%]

================================================================================ 1 passed in 0.10s =================================================================================
```

**Comment by Tomcli** [comment]
/close
by #628
