### ISSUE TITLE
REQUEST: New membership for DharmitD

### ISSUE THREAD

**Issue by DharmitD** [kubeflow/internal-acls#629]
/kind area/process

Please read the [guide lines](https://www.kubeflow.org/docs/about/contributing/#joining-the-community) for joining the Kubeflow GitHub org before opening an issue

**Please provide links to PRs or other contributions (2-3):**
https://github.com/kubeflow/kfp-tekton/pull/1359
https://github.com/kubeflow/pipelines/pull/10269

** Please list 2 existing members who are sponsoring your membership:**
@Tomcli 
@yhwang 
** Please test your PR **

Run

```
cd github_orgs
pytest test_org_yaml.py
```
Include the output in the PR

**Additional Instructions**

After your PR is merged please wait at least 1 hour for changes to propogate. 

If after an hour you haven't recieved an invite to join the GitHub org please open an issue.

You can contact build copy in #buildcop in kubeflow.slack.com

**Comment by yhwang** [comment]
/lgtm

@DharmitD thanks for your contributions!
