### ISSUE TITLE
Github handle @kubeflow/kubeflow-steering-committee does not exist

### ISSUE THREAD

**Issue by StefanoFioravanzo** [kubeflow/internal-acls#660]
Hey @jbottum @andreyvelich @terrytangyuan @johnugeorge @james-jwu I was trying to tag the KSC in a new issue and noticed that the handle defined here https://github.com/kubeflow/internal-acls/pull/650 does not exist in GH. Not sure if that file also syncs GH groups or not.

**Comment by terrytangyuan** [comment]
Oh I see. It's not visible to others

**Comment by terrytangyuan** [comment]
Let's see if https://github.com/kubeflow/internal-acls/pull/661 fixes it. Somehow it was using "secret" as default so I changed it to "closed" to be consistent with others
